// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VroomWiki.Data;

#nullable disable

namespace VroomWiki.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250220101759_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Models.ConfigColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Color");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            Name = "Piros"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Kék"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Zöld"
                        });
                });

            modelBuilder.Entity("Models.ConfigEngine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Co2Emission")
                        .HasColumnType("float");

                    b.Property<float>("FuelConsumption")
                        .HasColumnType("float");

                    b.Property<string>("FuelType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Horsepower")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Engine");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Co2Emission = 136f,
                            FuelConsumption = 6f,
                            FuelType = "Benzin",
                            Horsepower = 115,
                            Name = "1.5 TSI"
                        },
                        new
                        {
                            Id = 1,
                            Co2Emission = 140f,
                            FuelConsumption = 6.1f,
                            FuelType = "Benzin",
                            Horsepower = 150,
                            Name = "1.5 TSI"
                        },
                        new
                        {
                            Id = 2,
                            Co2Emission = 124f,
                            FuelConsumption = 5.4f,
                            FuelType = "Benzin(mild) Hybrid",
                            Horsepower = 150,
                            Name = "1.5 eTSI"
                        },
                        new
                        {
                            Id = 3,
                            Co2Emission = 128f,
                            FuelConsumption = 4.8f,
                            FuelType = "Gázolaj",
                            Horsepower = 150,
                            Name = "2.0 TDI"
                        },
                        new
                        {
                            Id = 4,
                            Co2Emission = 6f,
                            FuelConsumption = 0.3f,
                            FuelType = "Kombinált: benzin és elektromotor",
                            Horsepower = 150,
                            Name = "1.5 TSI Plug-In-Hybrid"
                        },
                        new
                        {
                            Id = 5,
                            Co2Emission = 170f,
                            FuelConsumption = 7.5f,
                            FuelType = "Benzin",
                            Horsepower = 265,
                            Name = "2.0 TSI"
                        },
                        new
                        {
                            Id = 6,
                            Co2Emission = 180f,
                            FuelConsumption = 7.9f,
                            FuelType = "Benzin",
                            Horsepower = 300,
                            Name = "2.0 TSI"
                        },
                        new
                        {
                            Id = 7,
                            Co2Emission = 192f,
                            FuelConsumption = 8.5f,
                            FuelType = "Benzin",
                            Horsepower = 333,
                            Name = "2.0 TSI"
                        });
                });

            modelBuilder.Entity("Models.ConfigTransmissionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("WheelDrive")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("TransmissionType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kézi 6 fokozatú",
                            WheelDrive = " Elsőkerék hajtás"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DSG váltó 7 fokozatú",
                            WheelDrive = " Elsőkerék hajtás"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DSG váltó 6 fokozatú",
                            WheelDrive = " Elsőkerék hajtás"
                        },
                        new
                        {
                            Id = 4,
                            Name = "DSG váltó 7 fokozatú",
                            WheelDrive = "Összkerék hajtás"
                        });
                });

            modelBuilder.Entity("Models.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CarpetType")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<float?>("Co2Emission")
                        .HasColumnType("float");

                    b.Property<int?>("Color_idId")
                        .HasColumnType("int");

                    b.Property<string>("ConfigName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Engine_idId")
                        .HasColumnType("int");

                    b.Property<float?>("FuelConsumption")
                        .HasColumnType("float");

                    b.Property<string>("FuelType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("Horsepower")
                        .HasColumnType("int");

                    b.Property<int?>("TransmissionTpye_idId")
                        .HasColumnType("int");

                    b.Property<int>("User_idId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("WheelDrive")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("WheelType")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("YearProd")
                        .HasColumnType("int");

                    b.Property<int?>("totalCost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Color_idId");

                    b.HasIndex("Engine_idId");

                    b.HasIndex("TransmissionTpye_idId");

                    b.HasIndex("User_idId");

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("Models.MainPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Chairman")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("Employees")
                        .HasColumnType("int");

                    b.Property<string>("Factories")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("Founded")
                        .HasColumnType("int");

                    b.Property<string>("Headquarters")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("History")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Owner")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Products")
                        .HasColumnType("longtext");

                    b.Property<string>("Profit")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("MainPage");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Chairman = "Thomas Schäfer",
                            Description = "A Volkswagen, rövidítve VW , egy német autómárka, amelyet 1937-ben alapították a Német Munkásfront (Deutsche Arbeitsfront) felkérésére, azzal a céllal, hogy beindítsa a tömeges motorizációt az akkori Harmadik Birodalomban. Székhelye az alsó-szászországi Wolfsburg városában található. A Volkswagen az ugyanilyen nevű konszern zászlóshajójának számít. A konszern 2016-ban és 2017-ben a világ legnagyobb autógyártójának számított",
                            Employees = 0,
                            Factories = "Bratislava, Wolfsburg, Dresten, Emden",
                            Founded = 1937,
                            Headquarters = "Wolfsburg",
                            Owner = "Volkswagen",
                            Products = "",
                            Profit = "322284000000"
                        });
                });

            modelBuilder.Entity("Models.PastModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Engine")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Horsepower")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("ReleaseDate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PastModel");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Description = "A Volkswagen UP! az új városi autó koncepciója, amely alapját képezi egy új kisautó-családnak, a Volkswagen Csoport által létrehozott New Small Family-nek (NSF). Ezen autócsalád tagja lesz az új Volkswagen UP!. A jelenlegi tervek szerint a kisautó-család tagjai szalon, szedán, kabrió, kétüléses és mini MPV típusú gépjárművek lesznek. A gyártási folyamatokat Pozsonyban fogják végezni. A kisautócsaládot a 2007-es Frankfurt Motor Show-n az (IAA)-n  leplezték le. Az UP! koncepciót a Volkswagen Csoport vezető tervezője, Walter de'Silva, és a Volkswagen személyautók főtervezője, Klaus Bischoff alkotta meg. Akkumulátoros elektromos változata a Volkswagen e-up!.",
                            Engine = "Otto-motor",
                            Horsepower = "60-115 lóerő",
                            Image = "https://en.wikipedia.org/wiki/File:2013_Volkswagen_Take_UP!_1.0.jpg",
                            Name = "Volkswagen up!",
                            ReleaseDate = 2011
                        },
                        new
                        {
                            Id = 7,
                            Description = "Magyarországon az alapmodell az 1,2-es benzines turbómotorral 4,96 millió forintba kerül, 76 ezerrel olcsóbb az azonos motorú Golfnál. Alapmotorral a 0–100 km/h 10,9 másodperc alatt van meg. A végsebessége 190 km/h. Közleményében a Volkswagen hangsúlyozta a modell tágasságát, amelynek alapköve, hogy méretnövekedés hatására 6,7 centivel bővült a lábhely. Az autó elődjeivel ellentétben nem osztozik a karosszériaelemeken a Golffal, hanem teljesen önálló modell. Formáját a januárban bemutatott NCC tanulmány inspirálta. Elődjénél szögletesebb a jármű, külsejét főként a vízszintes élek alkotják, jellegében azonban ugyanazt a hagyományos szedán formát hozza, mint eddig.",
                            Engine = "Otto-motor/dízelmotor",
                            Horsepower = "105-200 lóerő",
                            Image = "https://hu.wikipedia.org/wiki/F%C3%A1jl:VW_Jetta_VI_1.2_TSI_Comfortline_Platinumgrey.JPG",
                            Name = "Volkswagen Jetta",
                            ReleaseDate = 2010
                        },
                        new
                        {
                            Id = 8,
                            Description = "A nyolcadik generációs modellt 2014 novemberében vezették be az európai kontinensen, 2015 januárjában pedig az Egyesült Királyságban négyajtós limuzin és kombi kivitelben. Számos fejlett, vezetéstámogató rendszerekkel szerelték fel, beleértve a félautomata parkolórendszert, a gyalogos ütközés-elhárító rendszert és a sürgősségi vezető asszisztenst, amely automatikusan átveszi az irányítást a jármű felett, ha a sofőr sérülést szenvedett, vagy orvosi ellátásra szorul. A 2014-ben megválasztott Peugeot 308 modell után a 2015-ös 85-ik genfi kiállításon a VW Passat B8 nyerte el első helyezéssel a hét-kocsis döntőben Az Év Gépkocsija nevet, megelőzve a BMW i3 és a Tesla S modellt.",
                            Engine = "Otto-motor/dízelmotor",
                            Horsepower = "120-280 lóerő",
                            Image = "https://hu.wikipedia.org/wiki/F%C3%A1jl:VW_Passat_B8_Limousine_2.0_TDI_Highline.JPG",
                            Name = "Volkswagen Passat",
                            ReleaseDate = 2014
                        },
                        new
                        {
                            Id = 9,
                            Description = "A 2012-es párizsi autószalonon mutatták be a hetedik generációt. A modell a VW-konszern új MQB-platformjára épül. Az autó formája jelentősen különbözött az előző két generációétól. A 3 és 5 ajtós, kombi, valamint az itt már Sportsvannak átkereszrelt MPV modellek mellől végleg kikerült a kabrió a gyártásból.",
                            Engine = "Otto-motor/dízelmotor",
                            Horsepower = "77-360 lóerő",
                            Image = "https://hu.wikipedia.org/wiki/F%C3%A1jl:VW_Golf_1.6_TDI_BlueMotion_Technology_Comfortline_(VII)_%E2%80%93_Frontansicht,_31._Dezember_2012,_D%C3%BCsseldorf.jpg",
                            Name = "Volkswagen Golf",
                            ReleaseDate = 2012
                        },
                        new
                        {
                            Id = 10,
                            Description = "A második generációs Tiguant 2015 szeptemberében mutatták be a Frankfurti Nemzetközi Autókiállításon a 2016-os modellévre, és a Volkswagen Csoport MQB A2 platformjára építették. Eredetileg a rövid tengelytávú változatot leplezték le, amely 50 kg-mal (110 font) könnyebb, mint a korábbi Tiguan, miközben 60 mm-rel (2,4 hüvelyk) hosszabb, 30 mm-rel (1,2 hüvelyk) szélesebb, és a tengelytávja 77 mm-rel (3,0 hüvelyk) hosszabb. Ennek eredményeként a VW azt állította, hogy javult a belső tér, és a hátsó utasoknak 29 mm-rel (1,1 hüvelyk) több hely jutott a térdüknek. Továbbá, a hátsó üléspad aszimmetrikusan osztott, és akár 180 mm-ig (7,1 hüvelyk) hosszában is állítható.",
                            Engine = "Otto-motor/dízelmotor",
                            Horsepower = "113-316 lóerő",
                            Image = "https://en.wikipedia.org/wiki/File:VW_Tiguan_2.0_TSI_BlueMotion_Technology_4MOTION_Sound_(II)_%E2%80%93_Frontansicht,_24._Dezember_2017,_D%C3%BCsseldorf.jpg",
                            Name = "Volkswagen Tiguan",
                            ReleaseDate = 2016
                        },
                        new
                        {
                            Id = 1,
                            Description = "A Volkswagen Arteon egy német autógyártó, a Volkswagen által gyártott autó. Nagy családi autóként vagy középkategóriás autóként írják le, és ötajtós liftback vagy kombi karosszéria változatokban elérhető. Az Arteont 2017. március 6-án mutatták be a Genfi Autószalonon, majd a Chicagói Autószalonon is, az észak-amerikai piac számára. Az Arteon közvetlen utódja a CC-nek; azonban a Volkswagen bejelentette, hogy az Arteon magasabb kategóriát céloz meg, mint a CC. Az autó az MQB platformra épül.",
                            Engine = "Otto-motor/dízelmotor",
                            Horsepower = "148-276 lóerő",
                            Image = "https://en.wikipedia.org/wiki/File:2018_Volkswagen_Arteon_2.0.jpg",
                            Name = "Volkswagen Arteon",
                            ReleaseDate = 2017
                        },
                        new
                        {
                            Id = 2,
                            Description = "A Volkswagen T-Roc egy kisméretű crossover SUV, amelyet a német autógyártó, a Volkswagen gyárt. 2017-ben a Frankfurti Autószalonon mutatták be, és 2017 novemberében indították el. Az autó a Volkswagen Csoport MQB A1 platformjára épül, és általában a C-szegmenses Golf SUV megfelelőjeként tartják számon. A T-Roc a Tiguan és a kissé kisebb T-Cross között helyezkedik el, miközben méretben körülbelül megegyezik a Taigóval.",
                            Engine = "Otto-motor/dízelmotor",
                            Horsepower = "113-296 lóerő",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/VOLKSWAGEN_T-ROC_China_%2831%29.jpg/1024px-VOLKSWAGEN_T-ROC_China_%2831%29.jpg",
                            Name = "Volkswagen T-Roc",
                            ReleaseDate = 2017
                        },
                        new
                        {
                            Id = 3,
                            Description = "A Volkswagen ID.3 egy alsó középkategóriás, akkumulátoros elektromos autótípus, mely a Volkswagen első dedikált elektromos autótípusa. A hivatalos bemutatóra 2019. szeptember 9-én került sor a Frankfurti Autószalonon. Az ID.3 az első sorozatgyártású jármű, amely a kifejezetten elektromos autókhoz tervezett MEB-platformon alapul. Az MEB-platformban a hajtóakkumulátor a jármű padlójában foglal helyet. Az ID.3 a Volkswagen ID koncepciójárműre épül. Az ID az „intelligens tervezés” rövidítése. A 3-as szám a kompakt osztályt jelöli. 2021-ben a jármű negyedik lett az Európai Év Autója szavazáson. Az ID.3-at a „Prémium 50 000 euróig” kategóriában választották a győztesnek.",
                            Engine = "Villanymotor",
                            Horsepower = "150 kW",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/2020_Volkswagen_ID.3_1st_Front.jpg/1024px-2020_Volkswagen_ID.3_1st_Front.jpg",
                            Name = "Volkswagen ID.3",
                            ReleaseDate = 2020
                        },
                        new
                        {
                            Id = 4,
                            Description = "A Volkswagen T6 a Volkswagen Transporter sorozatának hatodik generációja, amelyet 2015-ben mutattak be. A T6 a márka ikonikus furgonja, amelyet személy- és teherautóként egyaránt forgalmaznak. A Volkswagen Transporter család az egyik legismertebb és legnépszerűbb furgon-sorozat a világon, és a T6 a sorozat egyik legfontosabb modellje, amely több mint öt évtizedes történettel rendelkezik.",
                            Engine = "Otto-motor/dízelmotor",
                            Horsepower = "89-201 lóerő",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/2017_Volkswagen_Transporter_T28_Highline_TDi_2.0_Front.jpg/1024px-2017_Volkswagen_Transporter_T28_Highline_TDi_2.0_Front.jpg",
                            Name = "Volkswagen Trasnporter",
                            ReleaseDate = 2016
                        },
                        new
                        {
                            Id = 5,
                            Description = "A Volkswagen Polo egy szuperminikategóriás (B-szegmens) autó, amelyet a német autógyártó, a Volkswagen gyárt 1975 óta. Európában és más piacokon világszerte értékesítik hatchback, szedán és kombi változatokban a gyártás teljes időszaka alatt. 2018-tól kezdődően hat különböző generációja készült a Polónak, amelyeket általában 'Series' vagy 'Mark' számokkal azonosítanak. Néhány generáció félidőben ráncfelvarráson esett át, és az ilyen frissített változatokat nem hivatalosan a szám után hozzáadott 'F' betűvel nevezik, például Mk2F. Néhány autós szaklap és egyes rajongók a ráncfelvarrásokat külön modellekként kezelik, így az előző generációk esetében a Polo Mk1-től Mk7-ig terjedő elnevezéseket használnak. Minden Polo modell egy két- vagy háromkarakteres Volkswagen Csoportos Típus számmal is azonosítható. Az hivatalos VW Polo történet az I. – IV. szériákat római számokkal[1] vagy arab számokkal jelöli, a ráncfelvarrott változatokat pedig 'Phase II' modelleként emlegetik. Az autó karosszériája az évek során változott, eredetileg hatchback volt, amely az Audi 50-ből származott.",
                            Engine = "Otto-motor/dízelmotor",
                            Horsepower = "65-192 lóerő",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Volkswagen_Polo_VI_%282021%29_IMG_5732.jpg/1280px-Volkswagen_Polo_VI_%282021%29_IMG_5732.jpg",
                            Name = "Volkswagen Polo",
                            ReleaseDate = 2017
                        });
                });

            modelBuilder.Entity("Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float?>("TotalIncome")
                        .HasColumnType("float");

                    b.Property<float?>("TotalSale")
                        .HasColumnType("float");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Sale");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            TotalIncome = 202.1f,
                            TotalSale = 10.1f,
                            Year = 2014
                        },
                        new
                        {
                            Id = 7,
                            TotalIncome = 213.4f,
                            TotalSale = 10.4f,
                            Year = 2015
                        },
                        new
                        {
                            Id = 8,
                            TotalIncome = 217.6f,
                            TotalSale = 10.3f,
                            Year = 2016
                        },
                        new
                        {
                            Id = 9,
                            TotalIncome = 228f,
                            TotalSale = 10.6f,
                            Year = 2017
                        },
                        new
                        {
                            Id = 10,
                            TotalIncome = 235.9f,
                            TotalSale = 10.8f,
                            Year = 2018
                        },
                        new
                        {
                            Id = 1,
                            TotalIncome = 251.9f,
                            TotalSale = 10.9f,
                            Year = 2019
                        },
                        new
                        {
                            Id = 2,
                            TotalIncome = 212.3f,
                            TotalSale = 9.3f,
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            TotalIncome = 249.2f,
                            TotalSale = 8.3f,
                            Year = 2021
                        },
                        new
                        {
                            Id = 4,
                            TotalIncome = 245.1f,
                            TotalSale = 8.3f,
                            Year = 2022
                        },
                        new
                        {
                            Id = 5,
                            TotalIncome = 322.2f,
                            TotalSale = 9.1f,
                            Year = 2023
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@admin.com",
                            Password = "admin01",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nagybela01@gmail.com",
                            Password = "bela01",
                            Username = "nbela007"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kissjanos@gmail.com",
                            Password = "janos1",
                            Username = "kjanos"
                        });
                });

            modelBuilder.Entity("Models.Configuration", b =>
                {
                    b.HasOne("Models.ConfigColor", "Color_id")
                        .WithMany()
                        .HasForeignKey("Color_idId");

                    b.HasOne("Models.ConfigEngine", "Engine_id")
                        .WithMany()
                        .HasForeignKey("Engine_idId");

                    b.HasOne("Models.ConfigTransmissionType", "TransmissionTpye_id")
                        .WithMany()
                        .HasForeignKey("TransmissionTpye_idId");

                    b.HasOne("Models.User", "User_id")
                        .WithMany()
                        .HasForeignKey("User_idId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color_id");

                    b.Navigation("Engine_id");

                    b.Navigation("TransmissionTpye_id");

                    b.Navigation("User_id");
                });
#pragma warning restore 612, 618
        }
    }
}
